### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by lizjegede** [codebar/new-manual#2]
- [x] Set up CI pipeline

**Comment by dubhcait** [comment]
Have a think about how you want to deploy your app, could be a chance to try something a little different. Say a different provider or a different want. It could be something to vary your experience. That is if you haven't deployed it already. Plus CI,  if you haven't had a play with GitHub actions they can be fun too. There is a good bit you can do with eslint or jshint for CI or a pre-commit/pre-push hook.
